select FLAVOR


from (SELECT FLAVOR ,TOTAL_ORDER FROM FIRST_HALF

      UNION ALL

      SELECT FLAVOR, TOTAL_ORDER FROM JULY) as total_table

group by FLAVOR

ORDER BY SUM(TOTAL_ORDER) DESC
    LIMIT 3;